# Generated by Django 5.0.3 on 2024-05-28 11:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_accessrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[app.models.maximum_length_string]),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=30, validators=[app.models.maximum_length_string]),
        ),
    ]
